name: solr-context-path

services:
  solr-context-path:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        SOLR_RELEASE_TAG: ${SOLR_RELEASE_TAG}
    image: ${SOLR_IMAGE_NAME}:${SOLR_IMAGE_TAG}
    container_name: solr-context-path
    hostname: solr-context-path
    networks:
      - solr-network
    volumes:
      - solr-data:/var/solr/data
    ports:
      - ${SOLR_PORT}:${SOLR_PORT}
    environment:
      CONTEXT_PATH: ${CUSTOM_SOLR_CONTEXT_PATH}
      SOLR_PORT: ${SOLR_PORT}

networks:
  solr-network:

volumes:
  solr-data:
    driver: local